version: "3.8"
services:
  mongo-db:
    container_name: mongo-db
    image: mongo
    ports:
      - $MONGODB_PORT:27017
    volumes:
      - mongovolume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
  express-js:
    depends_on:
      - mongo-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $PORT:$PORT
volumes:
  mongovolume: